title: First Github Page
author: Tushar
email: tushi.fire@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  First Github page let see how it looks
  
theme: minima
# social links
twitter_username: tushar_fire # DO NOT include the @ character, or else the build will fail!
github_username:  tushifire # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
